* * * * * Import Dump * * * * *
false
Importing dump in the dati_ais_2018 database
You are now connected to database "dati_ais_2018" as user "postgres".
ERROR:  table "ais_data" does not exist
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 237; 1259 290839 TABLE ais_data postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  type "geometry" does not exist
LINE 19:     geom geometry,
                  ^
    Command was: CREATE TABLE ais_data (
    date_time timestamp with time zone,
    mmsi character varying(9),
    course double precision,
...
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "public.ais_data" does not exist
    Command was: ALTER TABLE public.ais_data OWNER TO postgres;


pg_restore: [archiver (db)] Error from TOC entry 4279; 0 290839 TABLE DATA ais_data postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "ais_data" does not exist
    Command was: COPY ais_data (date_time, mmsi, course, speed, heading, imo, ship_name, callsign, ship_type, a, b, c, d, draught, destinatio...
WARNING: errors ignored on restore: 3
Done
Getting last datetime
ERROR:  relation "ais_data_clean" does not exist
LINE 1: SELECT max(date_time) FROM ais_data_clean;
                                   ^
last_time=0
Removing duplicates
You are now connected to database "dati_ais_2018" as user "postgres".
ERROR:  relation "ais_data_clean" does not exist
LINE 1: INSERT INTO ais_data_clean SELECT DISTINCT date_time,mmsi,co...
                    ^
ERROR:  relation "srp_dataset" does not exist
LINE 1: INSERT INTO srp_dataset SELECT DISTINCT date_time,mmsi,cours...
                    ^
Done
Starting setup
ERROR:  relation "srp_dataset" does not exist
LINE 1: SELECT max(date_time) FROM srp_dataset;
                                   ^
python: can't open file '/home/angelica/Git/osiris/knn/setup.py': [Errno 2] No such file or directory
Done
Running training
ERROR:  relation "srp_dataset" does not exist
LINE 1: SELECT max(record_id) FROM srp_dataset;
                                   ^
KNN
python: can't open file '/home/angelica/Git/osiris/knn/train.py': [Errno 2] No such file or directory
Done
